sudo: false

language: node_js

node_js:
    - 6
    - 8
    - 9
    - 10

matrix:
    fast_finish: true

cache:
    directories:
        - node_modules

before_install:
    - npm config set spin false
    - npm config set progress false
    - npm install -g npm

install:
    - npm prune
    - npm update --no-save

script:
    - npm test
    - npm install . -g >/dev/null && npm uninstall . -g >/dev/null
    - mkdir -p "/tmp/$TRAVIS_REPO_SLUG" && cd "/tmp/$TRAVIS_REPO_SLUG" && npm init -y >/dev/null
    - npm install "$TRAVIS_BUILD_DIR" >/dev/null && npm uninstall "$TRAVIS_BUILD_DIR" >/dev/null
    - node -e "const config = require('@$TRAVIS_REPO_SLUG');"
    - cd "$TRAVIS_BUILD_DIR"

deploy:
    - provider: npm
      email: npm@whizark.com
      api_key:
          secure: KvRRj+ForrkmlFmbMIHCqiM4D/YZCaB0aqr1EPSr7547XiIzHrjYCOuleY8HKmHAg1/9JIn0nh5PcLDCPnmLE9r2fSH5vPShpH77aStIGsi5IxAUwqRkOY3z3i1sSqcn9cUMbpaPgg+yInx2peAqgL/JtxOBbrp4d8YVX1CwY9r9FzCwz0r82YOKBxEPF1S0t+WBE5oQSz7T1GrY4EauJTzduP2RgJSH65/FaYRj6gj4a1NuA46AXZnHDhMR+HSQTpN+i3IgQ67Zz74zlvQwz/mKvowSdyXx6NfV0UxUr+oVAabdB5OvC/QwsI675LLHph6I+5R8RZc1zueNDCIXg8UegKns3bZn87IYd6iI/HbprQROhjhx+X8WKEEBm15bZWyn9t661cCCemk69VcIhKbPoIbatTCxbR2OKp2UpSlaYRAMfN+aO4M0YvT7Ai1yuAyuZ6pGkG+gFcLyg74cHfhnBemgIGVQRyD405M1LxGZsjushz+o3rZPZYAej4Q9tniSMYxO7D8/pegnQ3dymK40KewOqwah8WgtqJwr2KcgA4lXoM16OBScUsDhkCnGOtxZbWON0yM13VD2g7Qu9dU7Pv6O0a5Z1amzjCKgQNdY7PWDhN19tBcpE1xB92bsTm8f/f2jDVEEnqjS2DLAnvUqJWyakFQVmncXWaSpKP8=
      on:
          node: 8
          repo: whizark/stylelint-config
          branch: master
          tags: true

notifications:
    email: false

    slack:
        rooms:
            - secure: eqcnoltXfGZCTj+SkP4OCC8zVQDJZUpKbyE8sFU+bYTWaw/4+8Mb1x/kW6JNm/edKiVVnK3oG1xxed6L4hS6rd1m97xlh6cgbYp/Xg9xWxXGaA+z0Sf2U0IC1jPDCxlk9/SkLx8LIa2aEYy0ZgMSE//40GwOpGi8iWKqqL0llm8KmHg0+gzyE3DXzwZSS1d9mcR02gs1/NN2NWrNcHKXfPZNGjCdyBti31HGek0UmZI2cMTQB8HDz+VSUooW7Gza3zAbqoT4AOHMoDWYtSaYD1Iivsv1Cx2midv+91Z8LomUWg9+dLvSQoKtNSzt1+YYTkaUvYcBklIucASnZcNALquIjhs7QE5VX6qwgEX4hVCnqVYWXOwKXgKq6Pqwc7h2MVSkuXXC/FgkMyv3XO09e6dGa33CLpaG04D6v2ResvCn+WvtipDLuy4bkWKopUfJ+zmLiqXikaLBNJsRyUUwvsfW12JLyOkA86onVwn3wjMHhf+Jb0rwhrbD5GLKr6HwFXcpn1lFxd/Tn0aTVSd/hoUkYc8iCE1F6gEAt2JygdYssdhgOUlFGEkAF2geutFzI4byScJmpmM6QU7hEqlRp6EJLWh8oOKNgIFwR7ybFmRTzhTKhMThuPNw4009J0iBclMCGWK7Bsh90abPLoMQBYqovrRjcMK1bAmbUpgwfYo=
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
