sudo: false

language: node_js

node_js:
    - 8
    - 10
    - 11
    - 12

matrix:
    fast_finish: true

cache:
    directories:
        - node_modules

before_install:
    - npm config set spin false
    - npm config set progress false
    - npm install -g npm

install:
    - npm prune
    - npm update --no-save

script:
    - npm test
    - npm install . -g >/dev/null && npm uninstall . -g >/dev/null
    - mkdir -p "/tmp/$TRAVIS_REPO_SLUG" && cd "/tmp/$TRAVIS_REPO_SLUG" && npm init -y >/dev/null
    - npm install "$TRAVIS_BUILD_DIR" >/dev/null && npm uninstall "$TRAVIS_BUILD_DIR" >/dev/null
    - node -e "const config = require('@$TRAVIS_REPO_SLUG');"
    - cd "$TRAVIS_BUILD_DIR"

deploy:
    - provider: npm
      email: npm@whizark.com
      api_key:
          secure: CawcchqOmEHv/4tGcEzYjbhbXJYa2Oo0MhRH0uUD2NzDhPQslxbcjDMhOnBitZa0xy15E1MDbDSJeEWNKuvuKNrvA3AgGULTRlHy8mlRvTWyM4+h+j4h5GoHpTBaAXdbsv/tjUjQCD0frt3vbCZGDOaCMhw8LKaSMzptDrPht4YCUNztkRkCVnXRpfCDobC1FsEU6mRcuctLVgdNZUwvavChp0JcBGGibjJ8nxKwhvK0ocHCttCSIQ1aMyeUFZM8AKNBgQNRJ8DV/fMmO0fUYVbfHv6B+aBwSGOn23iW5uPgKlm8WR1fDguzc+0nyvRf0ZqGsr72goJz/feMC6uWr05sG4v1/gB5iJ5uNMGlQrJqQKxVmvITpBOErqy96Y6s2bq7qfNVsu9G6v3vBUqxgTAez89zvLpXrzH2nnuERZCG8+Vj3z3GGfAEGnj+7GXwd9iQ7AOa9xIAnSlHJ8oCLmVSJo151I7XhMGHrNsYWyWNGt0oA/qPKOJ2BTvjy6/up/7lMReeS2XvEwXtVwBZJZn4SJdSPbvxClzhE8qfUPl3ycsJ+L7UiNrbeKbdZPrupvM0VPVFJuZ8o0EfrtI5vlxSUjgxJ41fj3416x5O2StTWaL8FwhdzrW6hihSyi3f5uARZ3AvIippQCQUk/5hgXEZ5HnC89/4tkr3zGBhBLc=
      on:
          node: 8
          repo: whizark/stylelint-config
          branch: master
          tags: true

notifications:
    email: false

    slack:
        rooms:
            - secure: eqcnoltXfGZCTj+SkP4OCC8zVQDJZUpKbyE8sFU+bYTWaw/4+8Mb1x/kW6JNm/edKiVVnK3oG1xxed6L4hS6rd1m97xlh6cgbYp/Xg9xWxXGaA+z0Sf2U0IC1jPDCxlk9/SkLx8LIa2aEYy0ZgMSE//40GwOpGi8iWKqqL0llm8KmHg0+gzyE3DXzwZSS1d9mcR02gs1/NN2NWrNcHKXfPZNGjCdyBti31HGek0UmZI2cMTQB8HDz+VSUooW7Gza3zAbqoT4AOHMoDWYtSaYD1Iivsv1Cx2midv+91Z8LomUWg9+dLvSQoKtNSzt1+YYTkaUvYcBklIucASnZcNALquIjhs7QE5VX6qwgEX4hVCnqVYWXOwKXgKq6Pqwc7h2MVSkuXXC/FgkMyv3XO09e6dGa33CLpaG04D6v2ResvCn+WvtipDLuy4bkWKopUfJ+zmLiqXikaLBNJsRyUUwvsfW12JLyOkA86onVwn3wjMHhf+Jb0rwhrbD5GLKr6HwFXcpn1lFxd/Tn0aTVSd/hoUkYc8iCE1F6gEAt2JygdYssdhgOUlFGEkAF2geutFzI4byScJmpmM6QU7hEqlRp6EJLWh8oOKNgIFwR7ybFmRTzhTKhMThuPNw4009J0iBclMCGWK7Bsh90abPLoMQBYqovrRjcMK1bAmbUpgwfYo=
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
