sudo: false

language: node_js

node_js:
    - 4
    - 6
    - 7

matrix:
    fast_finish: true

cache:
    directories:
        - node_modules

before_install:
    - npm config set spin false
    - npm config set progress false
    - npm install -g npm

install:
    - npm prune
    - npm update

script:
    - npm install . -g >/dev/null && npm uninstall . -g >/dev/null
    - mkdir -p "/tmp/$TRAVIS_REPO_SLUG" && cd "/tmp/$TRAVIS_REPO_SLUG" && npm init -y >/dev/null
    - npm install "$TRAVIS_BUILD_DIR" >/dev/null && npm uninstall "$TRAVIS_BUILD_DIR" >/dev/null
    - node -e "const config = require('@$TRAVIS_REPO_SLUG');"
    - cd "$TRAVIS_BUILD_DIR"
    - |
        if [ "$TRAVIS_PULL_REQUEST" = 'false' ] && [ -n "$TRAVIS_TAG" ]; then
            npm test
        fi

deploy:
    - provider: npm
      email: npm@whizark.com
      api_key:
          secure: JQO6QSRFQw9cKpfwFCdHJXTCnqk6Y3hu36M3gCmsL25mW7HnBJqxbxUx0q0LecBSQQt87bs+9/SgZ2p+/vNNiksAmgSJ4k8kNTyy2a5Irc91xOZlv+rbuMQC0MccWpEIi0x+fvlRqXyfb4ikgCdHmglXLPfdnZ8oAdaAzCw1yubeuiRWXoD/Sw44HoFkZgNd8vPHdCPSTqGZkZqBxc5R93j35nhPboZEJMEKs7NLanld3HjWv49FKV0YY108C5kh/ROSBELXYPO6I2puZUZ6qYSmuzTdg07Cz9WgeXgf9h9ZmdAzTpgupJcL7ytVxPaQQOTrttw9cx7Wruk2f3z1prJr+bH7qv8Kn5X+MnyQ1sI6iRMfRzOQyAmsHD6cDJ1HHkqD0+xrcsc+AaVQ8NhMzDxyVnAITi3mXDjwJq0C9lPJXBbA9p4Q69Zo0OKloQrZTQf47uHTgOyEJqy5LmTz6wjqcQYPd3DdTtBmao+vguD0fFeqbMAHK/cV9ALW4wSh4KtMvSBw73ce//bMtXK7EuZKkcUkPkyeLpGAkY0tCafUm5/sM7VjGYdRc+ZxSEzAhICwEt56efc3dIdPqIJFjtkjpqV/j90OA/2/eibWZb+OjVd4GtJZeauetRnG7SEgFKNbw1v8pBTFJZn6D743p4N9R7Mrmc6QtdvDRGMU2PU=
      on:
          node: 6
          repo: whizark/stylelint-config
          branch: master
          tags: true

notifications:
    email: false

    slack:
        rooms:
            - secure: eqcnoltXfGZCTj+SkP4OCC8zVQDJZUpKbyE8sFU+bYTWaw/4+8Mb1x/kW6JNm/edKiVVnK3oG1xxed6L4hS6rd1m97xlh6cgbYp/Xg9xWxXGaA+z0Sf2U0IC1jPDCxlk9/SkLx8LIa2aEYy0ZgMSE//40GwOpGi8iWKqqL0llm8KmHg0+gzyE3DXzwZSS1d9mcR02gs1/NN2NWrNcHKXfPZNGjCdyBti31HGek0UmZI2cMTQB8HDz+VSUooW7Gza3zAbqoT4AOHMoDWYtSaYD1Iivsv1Cx2midv+91Z8LomUWg9+dLvSQoKtNSzt1+YYTkaUvYcBklIucASnZcNALquIjhs7QE5VX6qwgEX4hVCnqVYWXOwKXgKq6Pqwc7h2MVSkuXXC/FgkMyv3XO09e6dGa33CLpaG04D6v2ResvCn+WvtipDLuy4bkWKopUfJ+zmLiqXikaLBNJsRyUUwvsfW12JLyOkA86onVwn3wjMHhf+Jb0rwhrbD5GLKr6HwFXcpn1lFxd/Tn0aTVSd/hoUkYc8iCE1F6gEAt2JygdYssdhgOUlFGEkAF2geutFzI4byScJmpmM6QU7hEqlRp6EJLWh8oOKNgIFwR7ybFmRTzhTKhMThuPNw4009J0iBclMCGWK7Bsh90abPLoMQBYqovrRjcMK1bAmbUpgwfYo=
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
